"""Metadata scrub and audit — guarantee clean plain-text output."""

from __future__ import annotations

import re

from humanhand.domain.types import ScrubFinding, ScrubReport


def scrub_output(text: str) -> ScrubReport:
    """Remove metadata-like markers from candidate output and normalize.

    Guarantees the returned text is plain UTF-8 with LF newlines,
    no BOM, no hidden wrappers, and exactly one trailing newline.

    Args:
        text: Candidate output text (possibly with metadata).

    Returns:
        ScrubReport with cleaned_text, findings, and modification count.
    """
    cleaned = text
    findings: list[ScrubFinding] = []
    mods = 0

    # 1. Remove BOM
    if cleaned.startswith("﻿"):
        findings.append(
            ScrubFinding(
                category="bom",
                location="header",
                description="UTF-8 BOM removed",
                removed=True,
            )
        )
        cleaned = cleaned[1:]
        mods += 1

    # 2. Remove JSON wrapper (text wrapped in {"text": "..."} or similar)
    json_wrapper_pattern = r'^\s*\{\s*"[^"]+"\s*:\s*"'
    if re.match(json_wrapper_pattern, cleaned):
        findings.append(
            ScrubFinding(
                category="json_wrapper",
                location="header",
                description="JSON wrapper structure detected and removed",
                removed=True,
            )
        )
        # Extract text between outermost quotes after the first colon+quote
        cleaned = _unwrap_json_text(cleaned)
        mods += 1

    # 3. Remove model/provenance tags
    model_tag_patterns = [
        (r"\[Model:\s*[^\]]+\]", "model_tag", "Model tag removed"),
        (r"\[AI\s*[Gg]enerated[^\]]*\]", "ai_tag", "AI generation tag removed"),
        (r"\[Provenance:[^\]]+\]", "provenance", "Provenance tag removed"),
        (r"^\s*[-*]+\s*AI\s*[-*]+\s*$", "ai_separator", "AI separator removed"),
        (r"Generated by\s+\S+", "gen_by", "Generated-by marker removed"),
    ]
    for pattern, cat, desc in model_tag_patterns:
        if re.search(pattern, cleaned, re.IGNORECASE | re.MULTILINE):
            findings.append(
                ScrubFinding(category=cat, location="body", description=desc, removed=True)
            )
            cleaned = re.sub(pattern, "", cleaned, flags=re.IGNORECASE | re.MULTILINE)
            mods += 1

    # 4. Remove markdown code fences wrapping entire output
    stripped = cleaned.strip()
    if stripped.startswith("```") and stripped.endswith("```"):
        findings.append(
            ScrubFinding(
                category="code_fence",
                location="body",
                description="Markdown code fence wrapping removed",
                removed=True,
            )
        )
        # Remove opening fence (with optional language tag) and closing fence
        cleaned = re.sub(r"^```[a-zA-Z]*\s*\n", "", cleaned.strip(), count=1)
        cleaned = re.sub(r"\n```\s*$", "", cleaned, count=1)
        mods += 1

    # 5. Remove telemetry-like hidden fields
    telemetry_patterns = [
        (r'"request_id":\s*"[^"]*"', "telemetry", "Telemetry request_id removed"),
        (r'"model_version":\s*"[^"]*"', "telemetry", "Telemetry model_version removed"),
        (r'"generated_at":\s*"[^"]*"', "telemetry", "Telemetry timestamp removed"),
    ]
    for pattern, cat, desc in telemetry_patterns:
        if re.search(pattern, cleaned):
            findings.append(
                ScrubFinding(category=cat, location="embedded", description=desc, removed=True)
            )
            cleaned = re.sub(pattern, "", cleaned)
            mods += 1

    # 6. Normalize line endings to LF
    crlf_count = cleaned.count("\r\n")
    if crlf_count > 0:
        cleaned = cleaned.replace("\r\n", "\n")
        mods += 1
        findings.append(
            ScrubFinding(
                category="crlf",
                location="body",
                description=f"{crlf_count} CRLF sequences normalized to LF",
                removed=True,
            )
        )

    # 7. Strip trailing whitespace on each line
    lines = cleaned.split("\n")
    stripped_lines = [line.rstrip() for line in lines]
    if stripped_lines != lines:
        cleaned = "\n".join(stripped_lines)
        mods += 1
        findings.append(
            ScrubFinding(
                category="trailing_ws",
                location="body",
                description="Trailing whitespace stripped from lines",
                removed=True,
            )
        )

    # 8. Collapse multiple blank lines to at most one
    if "\n\n\n" in cleaned:
        cleaned = re.sub(r"\n{3,}", "\n\n", cleaned)
        mods += 1
        findings.append(
            ScrubFinding(
                category="blank_lines",
                location="body",
                description="Excess blank lines collapsed",
                removed=True,
            )
        )

    # 9. Ensure exactly one trailing newline
    cleaned = cleaned.rstrip("\n") + "\n"

    return ScrubReport(
        findings=tuple(findings),
        cleaned_text=cleaned,
        modifications=mods,
    )


def audit_text(text: str) -> ScrubReport:
    """Audit text for metadata-like markers without modifying.

    Args:
        text: Text to audit.

    Returns:
        ScrubReport with findings but unchanged text.
    """
    audit_findings: list[ScrubFinding] = []

    # BOM check (no removal)
    if text.startswith("﻿"):
        audit_findings.append(
            ScrubFinding(category="bom", location="header", description="UTF-8 BOM present")
        )

    # JSON wrapper check
    json_wrapper_pattern = r'^\s*\{\s*"[^"]+"\s*:\s*"'
    if re.match(json_wrapper_pattern, text):
        audit_findings.append(
            ScrubFinding(
                category="json_wrapper",
                location="header",
                description="JSON wrapper structure detected",
            )
        )

    # Model/provenance tag check
    model_tag_patterns = [
        (r"\[Model:\s*[^\]]+\]", "model_tag", "Model tag present"),
        (r"\[AI\s*[Gg]enerated[^\]]*\]", "ai_tag", "AI generation tag present"),
        (r"\[Provenance:[^\]]+\]", "provenance", "Provenance tag present"),
        (r"Generated by\s+\S+", "gen_by", "Generated-by marker present"),
    ]
    for pattern, cat, desc in model_tag_patterns:
        if re.search(pattern, text, re.IGNORECASE | re.MULTILINE):
            audit_findings.append(ScrubFinding(category=cat, location="body", description=desc))

    # Code fence check
    stripped = text.strip()
    if stripped.startswith("```") and stripped.endswith("```"):
        audit_findings.append(
            ScrubFinding(
                category="code_fence",
                location="body",
                description="Markdown code fence wrapping detected",
            )
        )

    # Telemetry-like hidden field check
    telemetry_patterns = [
        (r'"request_id":\s*"[^"]*"', "telemetry", "Telemetry request_id detected"),
        (r'"model_version":\s*"[^"]*"', "telemetry", "Telemetry model_version detected"),
        (r'"generated_at":\s*"[^"]*"', "telemetry", "Telemetry timestamp detected"),
    ]
    for pattern, cat, desc in telemetry_patterns:
        if re.search(pattern, text):
            audit_findings.append(ScrubFinding(category=cat, location="embedded", description=desc))

    # CRLF check
    if "\r\n" in text:
        audit_findings.append(
            ScrubFinding(
                category="crlf",
                location="body",
                description="CRLF line endings detected",
            )
        )

    # Trailing whitespace check
    for i, line in enumerate(text.split("\n")):
        if line != line.rstrip():
            audit_findings.append(
                ScrubFinding(
                    category="trailing_ws",
                    location="body",
                    description=f"Trailing whitespace on line {i + 1}",
                )
            )

    return ScrubReport(
        findings=tuple(audit_findings),
        cleaned_text=text,
        modifications=0,
    )


def _unwrap_json_text(text: str) -> str:
    """Attempt to extract plain text from a JSON wrapper."""
    # Try to find the first string value after a key
    match = re.search(r':\s*"((?:[^"\\]|\\.)*)"', text)
    if match:
        inner = match.group(1)
        # Unescape common escape sequences
        inner = inner.replace('\\"', '"').replace("\\n", "\n").replace("\\t", "\t")
        return inner
    return text
